### ISSUE TITLE
how can i run this?

### ISSUE THREAD

**Issue by bentech4u** [Maarten08/webapps#1]
i downloaded qt5webview.py and gave exec permission.

while running , got below

./qt5webview.py -u https://www.evernote.com
./qt5webview.py: line 5: syntax error near unexpected token `newline'
./qt5webview.py: line 5: `<!DOCTYPE html>'

what are dependencies needs to be installed ?

**Comment by Backup08** [comment]
Install with:
`sudo python setup.py install `

Run:
`qt5webview.py -u https://www.evernote.com`
or
`python qt5webview.py -u https://evernote.com`

Tested with Python 2.7.9, to check use
`python --version`

Depends on PyQt5 and optparse. Install with pip or apt,
`sudo pip install PyQt5`

**Comment by ffflorian** [comment]
@Maarten08

This doesn't really work...

```
$ pip --version
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
$ sudo pip install PyQt5
Downloading/unpacking PyQt5
  Could not find any downloads that satisfy the requirement PyQt5
Cleaning up...
No distributions at all found for PyQt5
```

**Comment by Backup08** [comment]
Try 
`sudo apt-get install python-pyqt5`
or
`sudo apt-get install python3-pyqt5`

**Comment by bentech4u** [comment]
i tried with pip

_root@enginon:/home/ben/Downloads# pip install PyQt5
Collecting PyQt5
  Could not find a version that satisfies the requirement PyQt5 (from versions: )
No matching distribution found for PyQt5_

here is my python version

ben@enginon:~/Downloads$ python --version
Python 2.7.12+

installed python-pyqt5 

$ sudo apt-get install python-pyqt5

after that tried starting qt5webview.py. but same error.

ben@enginon:~/Downloads$ ./qt5webview.py -u https://www.evernote.com
Traceback (most recent call last):
  File "./qt5webview.py", line 6, in <module>
    from PyQt5.QtWebKitWidgets import QWebView , QWebPage
ImportError: No module named QtWebKitWidgets

**Comment by bentech4u** [comment]
installed 

$apt-get install libqt5webkit5-dev python3-pyqt5.qtsvg python3-pyqt5.qtwebkit

And finally it started with below command

$ python3 qt5webview.py -u https://www.evernote.com
['https://www.evernote.com']
Image of format '' blocked because it is not considered safe. If you are sure it is safe to do so, you can white-list the format by setting the environment variable QTWEBKIT_IMAGEFORMAT_WHITELIST=
Image of format '' blocked because it is not considered safe. If you are sure it is safe to do so, you can white-list the format by setting the environment variable QTWEBKIT_IMAGEFORMAT_WHITELIST=
/usr/lib/python3/dist-packages/sessioninstaller/core.py:47: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gst
/usr/lib/python3/dist-packages/sessioninstaller/core.py:48: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
Falling back to package information
CRITICAL:Could not find any packages to operate on

**Comment by Backup08** [comment]
Can you run `lsb_release -a` and post the output?

**Comment by bentech4u** [comment]
ben@enginon:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety

**Comment by Backup08** [comment]
Check your PyQt5 version using:
`python3`  
`import PyQt5.QtCore` 
`print(PyQt5.QtCore.QT_VERSION_STR)`

I tried to reproduce the error on Ubuntu 16.04 live cd but don't get the same issue.

`python3`

> Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
> [GCC 5.3.1 20160330] on linux
> Type "help", "copyright", "credits" or "license" for more information.
>  import PyQt5.QtCore
>  print(PyQt5.QtCore.QT_VERSION_STR)
>  5.5.1
>  

`lsb_release -a`

> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04 LTS
> Release:	16.04
> Codename:	xenial

`sudo apt install python3-pyqt5`
`sudo apt-get install libqt5webkit5-dev python3-pyqt5.qtsvg python3-pyqt5.qtwebkit`
`sudo apt install git`
`git clone github.com/Maarten08/webapps.git`
`cd webapps/`
`sudo apt install python3-setuptools`
`sudo python3 setup.py install`
`qt5webview.py -u https://hckrnews.com`
`qt5webview.py -u https://evernote.com`
