### ISSUE TITLE
Desktop notification support

### ISSUE THREAD

**Issue by nebulade** [Maarten08/webapps#2]
Is there any way this could support desktop notification? I am not sure if this is only about setting another flag to the QWebView or if this requires additional UI components for the user to give permission.

**Comment by Backup08** [comment]
Which site/app do you want to show notifications from? The notify2 module can show messages in the desktop but is not included right now

**Comment by nebulade** [comment]
This is again my use-case of https://chat.cloudron.io
I can totally understand if this is out of focus for you.

**Comment by Backup08** [comment]
Checkout the latest version, I've tested on a notification demo site,
python qt5webview.py -u http://www.bennish.net/web-notifications.html -c

**Comment by nebulade** [comment]
Thanks, works just fine. Since it is intended for explicit use, the automatic grant seems correct.
